services:
  ledger-telegram-bot:
    build:
      context: ./src/ledger-telegram-bot
    container_name: ledger-telegram-bot
    restart: unless-stopped
    environment:
      - LEDGER_BOT_TOKEN=${LEDGER_BOT_TOKEN}
      - LEDGER_TRANSACTION_FILE_DIR=${LEDGER_TRANSACTION_FILE_DIR}
      - LEDGER_MAIN_TELEGRAM_USER_ID=${LEDGER_MAIN_TELEGRAM_USER_ID}
    volumes:
      - ./data/transactions:/data/transactions
